#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-source_map
Version  : 3.0.1
Release  : 4
URL      : https://rubygems.org/downloads/source_map-3.0.1.gem
Source0  : https://rubygems.org/downloads/source_map-3.0.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause MIT
BuildRequires : ruby
BuildRequires : rubygem-json
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec

%description
The `source_map` gem provides an API for parsing, and an API for generating source maps in ruby.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n source_map-3.0.1
gem spec %{SOURCE0} -l --ruby > rubygem-source_map.gemspec

%build
gem build rubygem-source_map.gemspec

%install
gem_dir=$(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .${gem_dir} \
--bindir .%{_bindir} \
source_map-3.0.1.gem

mkdir -p %{buildroot}${gem_dir}
cp -pa .${gem_dir}/* \
%{buildroot}${gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/source_map-3.0.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Generator/add_generated-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Generator/add_mapping-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Generator/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Generator/cdesc-Generator.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Generator/generated_col-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Generator/generated_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Generator/generated_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Generator/name_id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Generator/name_ids-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Generator/save-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Generator/serialize_mapping-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Generator/serialize_mappings%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Generator/source_id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Generator/source_ids-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Generator/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Generator/vlq-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Parser/cdesc-Parser.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Parser/parse_mapping-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Parser/parse_mappings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/Parser/undiff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/ParserError/cdesc-ParserError.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/VLQ/base64_decode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/VLQ/base64_encode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/VLQ/cdesc-VLQ.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/VLQ/decode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/VLQ/decode_array-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/VLQ/encode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/VLQ/from_vlq_signed-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/VLQ/to_vlq_signed-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/cdesc-SourceMap.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/from_json-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/from_s-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/mappings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/names-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/source_root-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/sources-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/SourceMap/version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/source_map-3.0.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/source_map-3.0.1/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/source_map-3.0.1/README.md
/usr/lib64/ruby/gems/2.2.0/gems/source_map-3.0.1/lib/source_map.rb
/usr/lib64/ruby/gems/2.2.0/gems/source_map-3.0.1/lib/source_map/generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/source_map-3.0.1/lib/source_map/parser.rb
/usr/lib64/ruby/gems/2.2.0/gems/source_map-3.0.1/lib/source_map/vlq.rb
/usr/lib64/ruby/gems/2.2.0/specifications/source_map-3.0.1.gemspec
